package com.ccjsd.web;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.ccjsd.business.jsd.Jsd;
import com.ccjsd.business.jsd.JsdRepository;
import com.ccjsd.util.CCJSDMaintenanceReturn;

@CrossOrigin
@Controller    // This means that this class is a Controller
@RequestMapping(path="/Jsds") // This means URL's start with /jsd (after Application path)
public class JsdController extends BaseController {
	@Autowired // This means to get the bean called jsdRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private JsdRepository jsdRepository;

	@GetMapping(path="/List") //instead of all, we use list 
	public @ResponseBody Iterable<Jsd> getAllJsds() {
		// This returns a JSON or XML with the jsds
		return jsdRepository.findAll();
	}
	
	@GetMapping(path="/Get")
	public @ResponseBody List<Jsd> getUSer (@RequestParam int id) {
		
		Optional<Jsd> u =jsdRepository.findById(id);
		return getReturnArray(u.get());
//		if (u.isPresent())
//			return u.get();
//		else
//			return null;
	}
	
//	@GetMapping(path="/Authenticate")
//	public @ResponseBody List<Jsd> getAuthenticate (@RequestParam String uname, @RequestParam String pwd) {
//	
//		Jsd jsd = jsdRepository.findByJsdName(uname);
//		return getReturnArray(jsd);
//	
//	}
	
	@PostMapping(path="/Add") // Map ONLY GET Requests
	public @ResponseBody CCJSDMaintenanceReturn addNewJsd (@RequestBody Jsd jsd) {
			try {
		jsdRepository.save(jsd);
		return CCJSDMaintenanceReturn.getMaintReturn(jsd);
	}
			catch (Exception e) {
		jsd = null;
	}
return CCJSDMaintenanceReturn.getMaintReturn(jsd);
}
	
	@GetMapping(path="/Remove") //Map ONLY GET requests
	public @ResponseBody CCJSDMaintenanceReturn deleteJsd (@RequestParam int id) {
		//@ResponseBody means the returned String is the response, not a view name
		//@ResponseParam means it is a parameter from the GET or POST request
		
	Optional <Jsd> jsd = jsdRepository.findById(id);
		try {
	jsdRepository.delete(jsd.get());
	//System.out.printlin("Jsd deleted:   " + jsd.get());
}
catch (Exception e) {
	jsd = null;
}
return CCJSDMaintenanceReturn.getMaintReturn(jsd);
}
	
	@PostMapping(path="/Change") 
	public @ResponseBody CCJSDMaintenanceReturn updateJsd (@RequestBody Jsd jsd) {
		try {
			jsdRepository.save(jsd);
		}
		catch (Exception e) {
			jsd = null;
		}
	return CCJSDMaintenanceReturn.getMaintReturn(jsd);
	}
}


	
	
	
	